version: '3'
services:
  angular:
    build: ads-client
    ports:
      - "4200:4200"
    volumes:
      - ./ads-client:/app

  nest: 
    build: ads-server 
    ports:
      - "3000:3000" 
    links:
      - mongo
    volumes:
      - ./ads-server:/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"